var bouton = document.getElementById("iguana");
var renards = document.getElementById("renards");
var verbs = document.getElementById("verbs");
bouton.addEventListener("click", function() {
document.getElementById("about").innerHTML = "The green iguana (Iguana iguana), also known as the American iguana or the common green iguana, is a large, arboreal, mostly herbivorous species of lizard of the genus Iguana. Usually, this animal is simply called the iguana. The green iguana ranges over a large geographic area; it is native from southern Brazil and Paraguay as far north as Mexico.A herbivore, it has adapted significantly with regard to locomotion and osmoregulation as a result of its diet. It grows to 1.7 m (5.6 ft) in length from head to tail, although a few specimens have grown more than 2 m (6.6 ft) with bodyweights upward of 20 lb (9.1 kg).Commonly found in captivity as a pet due to its calm disposition and bright colors, it can be very demanding to care for properly. Space requirements and the need for special lighting and heat can prove challenging to the hobbyist.The species was first officially described by Swedish botanist Carl Linnaeus in 1758.[6] Since then, numerous subspecies have been identified, but later classified as merely regional variants of the same species.";
});
renards.addEventListener("click", function() {
document.getElementById("about").innerHTML = "Foxes are small to medium-sized, omnivorous mammals belonging to several genera of the family Canidae. They have a flattened skull, upright, triangular ears, a pointed, slightly upturned snout, and a long bushy tail brush.Twelve species belong to the monophyletic true fox group of genus Vulpes. Approximately another 25 current or extinct species are always or sometimes called foxes; these foxes are either part of the paraphyletic group of the South American foxes, or of the outlying group, which consists of the bat-eared fox, gray fox, and island fox.[1]Foxes live on every continent except Antarctica. The most common and widespread species of fox is the red fox (Vulpes vulpes) with about 47 recognized subspecies.[2] The global distribution of foxes, together with their widespread reputation for cunning, has contributed to their prominence in popular culture and folklore in many societies around the world. The hunting of foxes with packs of hounds, long an established pursuit in Europe, especially in the British Isles, was exported by European settlers to various parts of the New World.";
});
verbs.addEventListener("click", function() {
document.getElementById("about").innerHTML = "A verb (from Latin verbum 'word') is a word (part of speech) that in syntax generally conveys an action (bring, read, walk, run, learn), an occurrence (happen, become), or a state of being (be, exist, stand). In the usual description of English, the basic form, with or without the particle to, is the infinitive. In many languages, verbs are inflected (modified in form) to encode tense, aspect, mood, and voice. A verb may also agree with the person, gender or number of some of its arguments, such as its subject, or object. Verbs have tenses: present, to indicate that an action is being carried out; past, to indicate that an action has been done; future, to indicate that an action will be done.For some examples:I washed the car yesterday.The dog ate my homework.John studies English and French.Lucy enjoys listening to music.Barack Obama became the President of the United States in 2009. (occurrence)Mike Trout is a center fielder. (state of being)";
});